site_name: Comparative Mythology
site_url: https://aninditabasu.github.io/comparative-mythology/
site_description: Examining the myths of ancient lands by comparing and contrasting the actors, actions, and places.
copyright: Copyright &copy; 2024 Anindita Basu

docs_dir: docs

theme:
  name: material
  logo: images/logo.jpg
  favicon: images/favicon.ico
  palette:
    primary: brown
  features:
    - toc.follow
    - navigation.top

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
    - search
    - macros
    - ultralytics:
        verbose: False
        enabled: True
        default_image: "https://aninditabasu.github.io/comparative-mythology/images/logo.jpg"
        add_desc: True
        add_image: True
        add_keywords: True
        add_share_buttons: True
        add_dates: False
        add_authors: False

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/anindita_basu
      name: Anindita Basu on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aninditabasu/
      name: Anindita Basu on LinkedIn

nav:
  - 'Home': 'index.md'
  - 'Here be dragons': 'myths/dragon_slaying.md'


